version: '3'

services:
  cppunit_test:
    build: ./vendor/cmake/
    image: denley/cmake
    working_dir: /opt/app
    entrypoint: /opt/app/docker-entrypoint.sh
    volumes:
      - .:/opt/app
      - ./src:/opt/app/src/
